export { ContactsTab } from './ContactsTab';
export { EducationTab } from './EducationTab';
export { FeaturesTab } from './FeaturesTab';
export { GeneralTab } from './GeneralTab';
export { PersonalDomainTab } from './PersonalDomainTab';
export { ProjectsTab } from './ProjectsTab';
export { SettingsTab } from './SettingsTab';
export { SideProjectsTab } from './SideProjectsTab';
export { SkillsTab } from './SkillsTab';
export { SpeakingTab } from './SpeakingTab';
export { VolunteeringTab } from './VolunteeringTab';
export { WorkExperienceTab } from './WorkExperienceTab';
export { AwardsTab } from './AwardsTab';
export { CertificationsTab } from './CertificationsTab';
export * from './PrintTab';
